// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace CloudCoinClientMAC
{
	public partial class BankViewController : NSViewController
	{
		public BankViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
