// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using CoreGraphics;

namespace CloudCoinMAC
{
	public partial class WindController : NSWindowController
	{
		public WindController (IntPtr handle) : base (handle)
		{
		}

        public override void WindowDidLoad()
        {
            base.WindowDidLoad();

            CGSize size = new CGSize();
            size.Width = 869;
            size.Height = 451;
            this.Window.MinSize = size;
            //this.Window.TitlebarAppearsTransparent = true;
            //this.Window.MovableByWindowBackground = true;

           // this.Window.BackgroundColor = NSColor.FromRgb(78, 47, 161);
        }
	}
}
