// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace CloudCoinMAC
{
	public partial class WindController : NSWindowController
	{
		public WindController (IntPtr handle) : base (handle)
		{
		}

        public override void WindowDidLoad()
        {
            base.WindowDidLoad();

            //this.Window.TitlebarAppearsTransparent = true;
            //this.Window.MovableByWindowBackground = true;

           // this.Window.BackgroundColor = NSColor.FromRgb(78, 47, 161);
        }
	}
}
