// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace CloudCoinMAC
{
	public partial class EchoViewController : NSViewController
	{
		public EchoViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
